User invites user
campuscode-alumni/multiplayer pull request #1
Opened 2019-04-05 00:29 UTC by vinimachado00

https://trello.com/c/OYsju3gL/9-usu%C3%A1rio-convida-participantes-para-evento

2019-04-05 15:56 UTC, HenriqueMorato requested changes

2019-04-05 15:56 UTC, HenriqueMorato commented on app/controllers/events_controller.rb
> +    @invited_user = User.find_by('nickname = :q OR email = :q', q: q)
O que acha de chamar direto para não criar uma variável utilizada uma vez só?

2019-04-05 15:56 UTC, HenriqueMorato commented on app/views/events/show.html.erb
> +  <%= simple_form_for @event, url: invite_event_path, method: :post do |f| %>
Aqui ficou meio estranho essa mistura de form_tag com simple_form. Você pode simular um form_tag com simple form colocando um symbol aqui tipo

```
<%= simple_form_for :invite, url: invite_event_path do |f| %>
  <%= f.input :q, label: t('form.new.invite.q') %>
  <%= f.submit t('form.new.invite.submit') %>
<% end %>
```

2019-04-05 15:56 UTC, HenriqueMorato commented on config/routes.rb
> +      post :invite
Como só tem uma linha dentro do member o que acha de trocar para a versão de uma linha e quando precisar abrir o bloco?

2019-04-05 15:56 UTC, HenriqueMorato commented on spec/factories/event_invites.rb
> +    event { nil }
Cuidado ao deixar `nil` aqui senão a Factory não funciona por padrão, tem que preencher todos os campos

2019-04-05 15:56 UTC, HenriqueMorato commented on spec/models/event_invite_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
O que acha de apagar esse arquivo se ele não está sendo utilizado

2019-04-06 02:44 UTC, L-Ghost commented on app/controllers/events_controller.rb
> +    @invited_user = User.find_by('nickname = :q OR email = :q', q: q)
Acho que é a melhor maneira sim.
Fizemos dessa maneira porque estávamos usando o código que ficou comentado. rs

2019-04-06 02:52 UTC, L-Ghost commented on app/views/events/show.html.erb
> +  <%= simple_form_for @event, url: invite_event_path, method: :post do |f| %>
Colocando dessa maneira o teste não está passando.
Ele tenta associar o campo de busca (:q) com o model Event.
Por isso que fizemos do jeito que está.

2019-04-06 02:55 UTC, L-Ghost commented on config/routes.rb
> +      post :invite
Vou modificar para ficar dessa maneira: `member {post :invite}`

2019-04-06 04:56 UTC, merged